import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { planVisualBible } from '../src/novel/visual-bible-planner.mjs'

const root = fileURLToPath(new URL('..', import.meta.url))

test('plans visual bible prompts by character tier without generating images', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'cine-make-visual-bible-'))
  try {
    await writeCharacters(workspace, [
      character({ name: '林夏', appearanceCount: 6, roleSignals: ['protagonist'], recommendedTier: 'S', visualHints: ['红围巾', '短发'] }),
      character({ name: '周辰', appearanceCount: 3, roleSignals: ['ally'], recommendedTier: 'A', visualHints: ['黑框眼镜'] }),
      character({ name: '老板娘', appearanceCount: 2, roleSignals: ['witness'], recommendedTier: 'B', visualHints: ['旧围裙'] }),
      character({ name: '路人甲', appearanceCount: 1, roleSignals: ['extra'], recommendedTier: 'C', visualHints: ['雨伞'] })
    ])

    const result = await planVisualBible({ runDir: workspace })

    assert.equal(result.referencePlanPath, path.join(workspace, 'visual-bible', 'character-reference-plan.md'))
    assert.equal(result.triviewPromptsPath, path.join(workspace, 'visual-bible', 'character-triview-prompts.md'))
    assert.deepEqual(result.counts, {
      characters: 4,
      S: 1,
      A: 1,
      B: 1,
      C: 1,
      imagePromptCharacters: 2
    })
    assert.deepEqual(result.warnings, [])

    const referencePlan = await readFile(result.referencePlanPath, 'utf8')
    assert.match(referencePlan, /# Character Reference Plan/)
    assert.match(referencePlan, /## Policy Notes/)
    assert.match(referencePlan, /No image files are generated by this planner/)
    assert.match(referencePlan, /## S-Tier/)
    assert.match(referencePlan, /林夏/)
    assert.match(referencePlan, /tri-view/)
    assert.match(referencePlan, /expression sheet/)
    assert.match(referencePlan, /costume\/prop lock/)
    assert.match(referencePlan, /## A-Tier/)
    assert.match(referencePlan, /周辰/)
    assert.match(referencePlan, /front-view/)
    assert.match(referencePlan, /## B-Tier/)
    assert.match(referencePlan, /老板娘/)
    assert.match(referencePlan, /text visual anchor only/)
    assert.match(referencePlan, /## C-Tier/)
    assert.match(referencePlan, /路人甲/)

    const prompts = await readFile(result.triviewPromptsPath, 'utf8')
    assert.match(prompts, /林夏/)
    assert.match(prompts, /tri-view character reference sheet/)
    assert.match(prompts, /expression sheet/)
    assert.match(prompts, /周辰/)
    assert.match(prompts, /front-view character reference/)
    assert.doesNotMatch(prompts, /老板娘/)
    assert.doesNotMatch(prompts, /路人甲/)

    const visualBibleEntries = await readdir(path.join(workspace, 'visual-bible'))
    assert.deepEqual(visualBibleEntries.sort(), [
      'character-reference-plan.md',
      'character-triview-prompts.md'
    ])
    assert.equal(visualBibleEntries.some((entry) => /\.(png|jpe?g|webp)$/iu.test(entry)), false)
  } finally {
    await rm(workspace, { recursive: true, force: true })
  }
})

test('infers conservative tiers and warns when S-tier count exceeds limit', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'cine-make-visual-bible-infer-'))
  try {
    await writeCharacters(workspace, [
      character({ name: '女主', appearanceCount: 2, roleSignals: ['主角'] }),
      character({ name: '男主', appearanceCount: 5, roleSignals: ['lead'] }),
      character({ name: '反派', appearanceCount: 3, roleSignals: ['antagonist'] }),
      character({ name: '导师', appearanceCount: 2, roleSignals: ['mentor'] }),
      character({ name: '店员', appearanceCount: 2, roleSignals: ['shopkeeper'] }),
      character({ name: '乘客', appearanceCount: 1, roleSignals: ['extra'] })
    ])

    const result = await planVisualBible({ runDir: workspace, maxSTier: 1 })

    assert.deepEqual(result.counts, {
      characters: 6,
      S: 2,
      A: 2,
      B: 1,
      C: 1,
      imagePromptCharacters: 4
    })
    assert.equal(result.warnings.length, 1)
    assert.match(result.warnings[0], /S-tier character count 2 exceeds max 1/)

    const prompts = await readFile(result.triviewPromptsPath, 'utf8')
    assert.match(prompts, /女主/)
    assert.match(prompts, /男主/)
    assert.match(prompts, /反派/)
    assert.match(prompts, /导师/)
    assert.doesNotMatch(prompts, /店员/)
    assert.doesNotMatch(prompts, /乘客/)
  } finally {
    await rm(workspace, { recursive: true, force: true })
  }
})

test('rejects missing or malformed characters bible clearly', async () => {
  const missingWorkspace = await mkdtemp(path.join(tmpdir(), 'cine-make-visual-bible-missing-'))
  const malformedWorkspace = await mkdtemp(path.join(tmpdir(), 'cine-make-visual-bible-malformed-'))
  try {
    await assert.rejects(
      planVisualBible({ runDir: missingWorkspace }),
      /Missing novel character bible: .*bible[/\\]characters\.json/
    )

    await mkdir(path.join(malformedWorkspace, 'bible'), { recursive: true })
    await writeFile(path.join(malformedWorkspace, 'bible', 'characters.json'), '{"name": "not an array"}\n', 'utf8')

    await assert.rejects(
      planVisualBible({ runDir: malformedWorkspace }),
      /Malformed novel character bible: .*characters\.json must contain an array/
    )
  } finally {
    await rm(missingWorkspace, { recursive: true, force: true })
    await rm(malformedWorkspace, { recursive: true, force: true })
  }
})

test('novel visual-bible CLI requires run and prints output paths', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'cine-make-visual-bible-cli-'))
  try {
    await writeCharacters(workspace, [
      character({ name: '林夏', appearanceCount: 6, roleSignals: ['protagonist'], recommendedTier: 'S' }),
      character({ name: '周辰', appearanceCount: 3, roleSignals: ['ally'], recommendedTier: 'A' })
    ])

    const missingRun = spawnSync(process.execPath, [
      'src/cli.mjs',
      'novel',
      'visual-bible'
    ], {
      cwd: root,
      encoding: 'utf8'
    })
    assert.notEqual(missingRun.status, 0)
    assert.match(missingRun.stderr, /novel visual-bible requires --run <value>/)

    const result = spawnSync(process.execPath, [
      'src/cli.mjs',
      'novel',
      'visual-bible',
      '--run',
      workspace,
      '--max-s-tier',
      '1'
    ], {
      cwd: root,
      encoding: 'utf8'
    })

    assert.equal(result.status, 0, result.stderr)
    assert.match(result.stdout, /Cine Make planned visual bible:/)
    assert.match(result.stdout, new RegExp(escapeRegExp(path.join(workspace, 'visual-bible', 'character-reference-plan.md'))))
    assert.match(result.stdout, new RegExp(escapeRegExp(path.join(workspace, 'visual-bible', 'character-triview-prompts.md'))))
    assert.match(result.stdout, /warnings: 0/)
  } finally {
    await rm(workspace, { recursive: true, force: true })
  }
})

async function writeCharacters(projectDir, characters) {
  const bibleDir = path.join(projectDir, 'bible')
  await mkdir(bibleDir, { recursive: true })
  await writeFile(path.join(bibleDir, 'characters.json'), `${JSON.stringify(characters, null, 2)}\n`, 'utf8')
}

function character(overrides) {
  return {
    name: 'Character',
    firstChapter: 'chapter-0001',
    appearanceCount: 1,
    roleSignals: [],
    visualHints: [],
    relationshipHints: [],
    chapters: ['chapter-0001'],
    ...overrides
  }
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
